name: release
on:
  push:
    tags:
      - 'v*'

env:
  REGISTORY: ghcr.io
  IMAGE_NAME: uc4w6c/jwtmock

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Check tagged branch
        run: |
          BRANCHS=$(git branch --contains ${{ github.ref_name }})
          set -- $BRANCHS
          for BRANCH in $BRANCHS ; do
            if [[ "$BRANCH" == "main" ]]; then
              exit 0
            fi
          done
          exit 1
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ${{ env.REGISTORY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build Docker Image
        run: |
          ./gradlew bootBuildImage
          docker tag ${{ env.REGISTORY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTORY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name}}
      - name: Push Docker Image
        run: |
          docker push ${{ env.REGISTORY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTORY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
